version: '3.8'
services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - tgnet
    volumes:
      - .:/app

  redis:
    image: redis:7.2-apline
    container_name: redis
    restart: always
    networks:
      - tgnet

  db:
    image: my.sql
    container_name: mysql
    environment:
      MYSQL_DATAVASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
      volumes:
        - mysqldata:/var/lib/mysql
      restart: always
      networks:
        -tgnet

volumes:
  mysqldata:
networks:
  tgnet:


